### ISSUE TITLE
VS 2017

### ISSUE THREAD

**Issue by nzbart** [olegsych/posh-vs#1]
The readme says:
>Makes Visual Studio 2015 command line tools available in PowerShell.

Is there any chance of making this support VS 2017 as well?

**Comment by olegsych** [comment]
I'm working on it now. The side-by-side installation of Visual Studio 2017 makes tools discovery more challenging than I thought. In the meantime, instead of running `Install-PoshVs` you can change your `$profile` manually and call `Import-BatchEnvironment` like this:

```
Import-BatchEnvironment "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat" 
```

**Comment by olegsych** [comment]
Pull request #3 added Visual Studio 2017 support in version `0.2`. If you have version `0.1` installed, simply 
```
PS>Update-Module posh-vs
```
Enjoy!
