### ISSUE TITLE
Import-VisualStudioEnvironment is cumulative

### ISSUE THREAD

**Issue by wtjones** [olegsych/posh-vs#6]
I tend to reload my profile with `.$profile` on occasion. I started noticing this error:
```
The input line is too long.
The syntax of the command is incorrect.
```
`$env:path` will show redundant lines added by `Import-VisualStudioEnvironment`. 

This may or may not be considered a bug, but the workaround is something like this:

```
if (!(Test-Path env:DevEnvDir)) {Import-VisualStudioEnvironment}
```

**Comment by Regenhardt** [comment]
I recently noticed the same error coming up every time I start my powershell. Thanks for the workaround. That should be in the package itself actually (or another fix somewhere).

**Comment by olegsych** [comment]
@wtjones Thanks for reporting this. I've implemented your suggestion and published a new version to the PowerShellGallery.
